### ISSUE TITLE
Update ember-cli-babel version?

### ISSUE THREAD

**Issue by backspace** [san650/ember-test-assets#10]
Hey, in `travis-web`, this addon is our last instance of this deprecation warning:

```
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: travis -> ember-test-assets -> ember-cli-babel
```

I could take on updating but I’m wondering if you’d want to update Ember CLI and everything and whether you have any particular desires for Ember version supports.

**Comment by san650** [comment]
@backspace it would be great to update this addon! I don't have any particular preference on a version, I'm fine with whatever you pick 😃 

Thank you!
